[package]
name = "xxhash_reference"
license = "MIT OR Apache-2.0"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Christopher Berner <christopherberner@gmail.com>"]

[dependencies]
libc = "0.2.125"

[build-dependencies]
cc = "1.0.73"