name: CI

on:
  pull_request:
  push: # required for actions/cache to work
    branches:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest", "ubuntu-24.04-arm"]

    runs-on: ${{ matrix.os }}

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.toml', '.github/workflows/*.yml', 'rust-toolchain') }}

      - name: Check for forbidden words
        run: "! grep --include='*.rs' -RE 'dbg!' ."
        if: runner.os != 'Windows'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Rust
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Install cargo-deny
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install --force --version 0.16.2 cargo-deny --locked

      - name: Install cargo-fuzz
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install --force --version 0.12.0 cargo-fuzz --locked

      - name: Install just
        if: steps.rust-cache.outputs.cache-hit != 'true'
        run: cargo install --force --version 1.36.0 just --locked

      - name: Compile
        run: cargo build --all-targets

      - name: Run tests
        run: just build test

      - name: Run fuzzer
        run: just fuzz_ci
        if: startsWith(matrix.os, 'ubuntu')

      - name: Clippy
        run: cargo clippy --all --all-targets -- -Dwarnings

      - name: Format
        run: cargo fmt --all -- --check

      - name: Run CPython wrapper tests
        if: runner.os != 'Windows'
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install --upgrade pip
          pip3 install maturin
          just test_py
